server:
  port: 8901

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: api-server1
          uri: http://localhost:8080
          predicates:
            - Query=api-server1
        - id: api-server2
          uri: http://localhost:8081
          predicates:
            - Query=api-server2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka

