server:
  port: 8901

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: api-client
          uri: http://localhost:8090
          predicates:
            - Path=/api/**
          filters:
            - SetRequestHeader=X-Request-Flag, true
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8090"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders: "*"
            allowedCredentials: true
            maxAge: 300000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka

